 - block:
 
    - name: DEBUG -                 🟢 API URL
      debug: 
        var: k8s_apiurl


    - name: DEBUG -                 🟢 API KEY
      debug: 
        var: k8s_apikey

    - name: OCP Login
      shell: |
        curl http://192.168.122.1:6080/oc -o /tmp/oc
        chmod 755 /tmp/oc
        /tmp/oc login --token={{ my_k8s_apikey }} --server={{ my_k8s_apiurl }} --insecure-skip-tls-verify
      ignore_errors: yes


    - name: Mitigate MYSQL Problem (NEW)
      shell: |
        /tmp/oc patch service mysql -n robot-shop --patch '{"spec": {"selector": {"service": "mysql"}}}'
        /tmp/oc set env deployment ratings -n robot-shop PDO_URL-
        /tmp/oc set env deployment load -n robot-shop ERROR=0
        /tmp/oc delete pod $(/tmp/oc get po -n robot-shop|grep shipping|awk '{print$1}') -n robot-shop --ignore-not-found

      ignore_errors: yes

    - name: Clean Incident and alerts
      shell: |
        WAIOPS_NAMESPACE=$(/tmp/oc get po -A|grep aiops-orchestrator-controller |awk '{print $1}')
        /tmp/oc project $WAIOPS_NAMESPACE
        USER=$(/tmp/oc get secret aiops-ir-core-ncodl-api-secret -o jsonpath='{.data.username}' | base64 --decode)
        PWD=$(/tmp/oc  get secret aiops-ir-core-ncodl-api-secret -o jsonpath='{.data.password}' | base64 --decode)
        USER_PASS=$USER:$PWD
        DATALAYER_ROUTE=$(/tmp/oc get route datalayer-api  -o jsonpath='{.status.ingress[0].host}')
        curl "https://$DATALAYER_ROUTE/irdatalayer.aiops.io/active/v1/alerts" --insecure --silent -X PATCH -u "${USER_PASS}" -d '{"state": "resolved"}' \
             -H 'Content-Type: application/json' -H "x-username:admin" -H "x-subscription-id:cfd95b7e-3bc7-4006-a4a8-a73a79c71255"
             
        curl "https://$DATALAYER_ROUTE/irdatalayer.aiops.io/active/v1/stories" --insecure --silent -X PATCH -u "${USER_PASS}" -d '{"state": "resolved"}' \
             -H 'Content-Type: application/json' -H "x-username:admin" -H "x-subscription-id:cfd95b7e-3bc7-4006-a4a8-a73a79c71255"
       
        /tmp/oc set env deployment load -n robot-shop ERROR=0
        /tmp/oc delete pod $(/tmp/oc get po -n robot-shop|grep shipping|awk '{print$1}') -n robot-shop --ignore-not-found
    
      ignore_errors: yes

    - name: Increase MYSQL Memory
      shell: |
        echo "---------------------------------------------------------------------------------------------------------------------------------------------------"
      ignore_errors: yes

    - name: Rollback GIT Commit
      shell: |
        echo "---------------------------------------------------------------------------------------------------------------------------------------------------"
      ignore_errors: yes
